# Use the official Node.js image as the base image
FROM node:14

# Install expo-cli globally
RUN npm install -g expo-cli

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the entire project directory into the container
COPY . .

# Start the Expo development server when the container runs
CMD ["npm", "start"]
